// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"
	"time"

	demo "go-microservices/service/gatewayService/internal/handler/demo"
	"go-microservices/service/gatewayService/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthInterceptor},
			[]rest.Route{
				{
					// ping
					Method:  http.MethodGet,
					Path:    "/ping",
					Handler: demo.PingHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/demo"),
		rest.WithTimeout(5000*time.Millisecond),
		rest.WithMaxBytes(1048576),
	)
}
