// Code generated by goctl. DO NOT EDIT.
package types

type ApiBaseReq struct {
	Version    string `json:"version,optional"`     // 版本号
	OsVersion  string `json:"os_version,optional"`  // 操作系统版本号
	DeviceId   string `json:"device_id,optional"`   // 设备id
	DeviceType int64  `json:"device_type,optional"` // 设备类型 0-安卓，1-IOS
	Hardware   string `json:"hardware,optional"`    // 设备名称
	SessionId  string `json:"session_id,optional"`  // 会话id
	Locale     string `json:"locale,optional"`      // 多语言
	Resolution string `json:"resolution,optional"`  // 屏幕分辨率
	Platform   string `json:"platform,optional"`    // 平台
}

type ApiBaseResp struct {
	Code    int64  `json:"code,omitempty"`
	Message string `json:"message,omitempty"`
}

type User struct {
	Id       int64  `json:"id,optional"`
	Username string `json:"username,optional"`
}

type UserDeleteReq struct {
	ApiBaseReq
	Id int64 `json:"id"`
}

type UserDeleteResp struct {
	ApiBaseResp
}

type UserInsertReq struct {
	ApiBaseReq
	Data User `json:"data"`
}

type UserInsertResp struct {
	ApiBaseResp
}

type UserListReq struct {
	ApiBaseReq
	Id         int64 `json:"id,optional"`
	PageNumber int64 `json:"page_number,optional"` //页码
	PageSize   int64 `json:"page_size,optional"`   //每页数量
}

type UserListResp struct {
	ApiBaseResp
	Data interface{} `json:"data"`
}

type UserUpdateReq struct {
	ApiBaseReq
	Data User `json:"data"`
}

type UserUpdateResp struct {
	ApiBaseResp
}
