// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"
	"time"

	user "go-microservices/service/adminService/internal/handler/user"
	"go-microservices/service/adminService/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthInterceptor},
			[]rest.Route{
				{
					// 删除
					Method:  http.MethodPost,
					Path:    "/delete",
					Handler: user.DeleteHandler(serverCtx),
				},
				{
					// 新增
					Method:  http.MethodPost,
					Path:    "/insert",
					Handler: user.InsertHandler(serverCtx),
				},
				{
					// 列表
					Method:  http.MethodPost,
					Path:    "/list",
					Handler: user.ListHandler(serverCtx),
				},
				{
					// 修改
					Method:  http.MethodPost,
					Path:    "/update",
					Handler: user.UpdateHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin/user"),
		rest.WithTimeout(5000*time.Millisecond),
		rest.WithMaxBytes(1048576),
	)
}
