// Code generated by goctl. DO NOT EDIT.
// Source: demo.proto

package client

import (
	"context"

	"go-microservices/proto/generate/demo"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	PingReq  = demo.PingReq
	PingResp = demo.PingResp

	Demo interface {
		// Ping pong
		Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingResp, error)
	}

	defaultDemo struct {
		cli zrpc.Client
	}
)

func NewDemo(cli zrpc.Client) Demo {
	return &defaultDemo{
		cli: cli,
	}
}

// Ping pong
func (m *defaultDemo) Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingResp, error) {
	client := demo.NewDemoClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
