// Code generated by goctl. DO NOT EDIT.
package types

type ApiBaseReq struct {
	Version string `json:"version,optional"` // 版本号
}

type ApiBaseResp struct {
	Status    string `json:"status,omitempty"`
	Message   string `json:"message,omitempty"`
	ErrorCode int64  `json:"error_code,omitempty"`
}

type PingReq struct {
	ApiBaseReq
	Ping string `json:"ping"`
}

type PingResp struct {
	ApiBaseResp
	Pong string `json:"pong"`
}
